### ISSUE TITLE
Rake aborted while running {sudo bundle exec rake redmine_git_hosting:fetch_changesets RAILS_ENV=production}

### ISSUE THREAD

**Issue by NisargPatel2022** [redmine-git-hosting/redmine_git_hosting#811] opened 2022-05-16 11:48 UTC
While running the command **sudo bundle exec rake redmine_git_hosting:fetch_changesets RAILS_ENV=production** I face error of rake aborted.
I am running this command because my gitolite repository does not gets reflected on redmine and its is showing empty repository even though it is not.
Please help me with following attached error : -

![Rake Aborted Error](https://user-images.githubusercontent.com/102032895/168586167-4770c3dc-df8a-49fa-acdc-3a7a04c13af1.png)

**Comment by XiMMiX** [comment] 2022-05-31 11:19
Looks like the same error as #805.

**Comment by prahal** [comment] 2022-09-27 00:24
@NisargPatel2022 if you were running the git master branch the issue is fixed in https://github.com/jbox-web/redmine_git_hosting/pull/815/commits/7c8f9e357296fe1c62e7af962e8c459bc435e8aa, else please provide at least your rails, redmine, ruby and redmine_git_hosting version so we can test the issue on a similar setup.

**Comment by PowerKiKi** [comment] 2022-12-15 16:18
Closed as per last comment

**Closed by PowerKiKi** 2022-12-15 16:18 UTC
