### ISSUE TITLE
Unable to install hooks via rake task

### ISSUE THREAD

**Issue by acosonic** [redmine-git-hosting/redmine_git_hosting#805] opened 2022-04-11 11:06 UTC
Code below shows error as well:

```
user@redmine:~/redmine$ RAILS_ENV=production rake redmine_git_hosting:install_gitolite_hooks
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.
The dependency ffi (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`.

 * Installing/updating Gitolite hooks:
rake aborted!
NameError: undefined local variable or method `block' for RedmineGitHosting::ConsoleLogger:Module
/home/user/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting/console_logger.rb:9:in `title'

```

**Comment by prahal** [comment] 2022-09-27 04:11
@acosonic  if you were running the git master branch the issue is fixed in https://github.com/jbox-web/redmine_git_hosting/commit/7c8f9e357296fe1c62e7af962e8c459bc435e8aa, else please provide at least your rails, redmine, ruby and redmine_git_hosting version so we can test the issue on a similar setup. You can get those infos from https://<your_redmine_uri>/admin/info.

**Comment by PowerKiKi** [comment] 2022-12-15 16:19
Closed as per last comment

**Closed by PowerKiKi** 2022-12-15 16:19 UTC
