### ISSUE TITLE
git cache issue viewing files

### ISSUE THREAD

**Issue by tomhub** [redmine-git-hosting/redmine_git_hosting#796] opened 2021-09-16 16:27 UTC
Hi, I have created test project with empty repository, which contains readme.md. When I click on readme.md, I get this error:
```
NameError (uninitialized constant #<Class:RedmineGitHosting::Cache::AbstractCache>::Timezone):
  
plugins/redmine_git_hosting/lib/redmine_git_hosting/cache/abstract_cache.rb:59:in `valid_cache_entry?'
plugins/redmine_git_hosting/lib/redmine_git_hosting/cache/database.rb:21:in `get_cache'
plugins/redmine_git_hosting/lib/redmine_git_hosting/cache.rb:22:in `get_cache'
plugins/redmine_git_hosting/lib/redmine_git_hosting/shell_redirector.rb:36:in `execute'
plugins/redmine_git_hosting/lib/redmine/scm/adapters/xitolite_adapter.rb:482:in `git_cmd'
plugins/redmine_git_hosting/lib/redmine/scm/adapters/xitolite_adapter.rb:133:in `entries'
plugins/redmine_git_hosting/lib/redmine/scm/adapters/xitolite_adapter.rb:121:in `entry'
app/models/repository.rb:200:in `entry'
app/controllers/repositories_controller.rb:149:in `entry_and_raw'
app/controllers/repositories_controller.rb:139:in `entry'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

This is running on:
```
Environment:
  Redmine version                4.2.2.stable
  Ruby version                   2.6.8-p205 (2021-07-07) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.33.0
  Filesystem                     
  Xitolite                       2.33.0
Redmine plugins:
  additionals                    3.0.4-master
  redmine_auditlog               0.0.5
  redmine_git_hosting            5.0.1-master
  redmine_privacy_terms          1.0.3
  redmine_spent_time             4.1.0
```

Afterwards, going back into repository tab:
```
Processing by RepositoriesController#show as HTML
  Parameters: {"id"=>"test"}
  Current user: admin (id=1)
git: error during get default branch: uninitialized constant #<Class:RedmineGitHosting::Cache::AbstractCache>::Timezone
Completed 500 Internal Server Error in 16ms (ActiveRecord: 4.3ms)
  
NameError (uninitialized constant #<Class:RedmineGitHosting::Cache::AbstractCache>::Timezone):
  
plugins/redmine_git_hosting/lib/redmine_git_hosting/cache/abstract_cache.rb:59:in `valid_cache_entry?'
plugins/redmine_git_hosting/lib/redmine_git_hosting/cache/database.rb:21:in `get_cache'
plugins/redmine_git_hosting/lib/redmine_git_hosting/cache.rb:22:in `get_cache'
plugins/redmine_git_hosting/lib/redmine_git_hosting/shell_redirector.rb:36:in `execute'
plugins/redmine_git_hosting/lib/redmine/scm/adapters/xitolite_adapter.rb:482:in `git_cmd'
plugins/redmine_git_hosting/lib/redmine/scm/adapters/xitolite_adapter.rb:133:in `entries'
app/models/repository/git.rb:102:in `scm_entries'
app/models/repository.rb:209:in `entries'
app/controllers/repositories_controller.rb:89:in `show'
plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:29:in `show'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```
The solution to nicely revert back to working 'Repository' tab, is to go to Administration -> Redmine Git Hosting -> Rescue -> select all 3 ticks and apply.

**Comment by tomhub** [comment] 2021-09-16 21:03
As a workaround, it seems after rescue, changing Plugins -> Redmine Git Hosting Pluging -> Cache tab to "cache disabled" the issue goes away.

**Comment by toastedcrumpets** [comment] 2021-11-12 08:27
Hey,
Just confirming I'm seeing this issue just when opening certain repositories. A full rescue fixes the issue but only temporarily.
I'm on an earlier version of redmine too.

Environment:
  Redmine version                4.1.5.stable
  Ruby version                   2.6.8-p205 (2021-07-07) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Mercurial                      4.8.2
  Bazaar                         2.8.0
  Git                            2.20.1
  Filesystem                     
  Xitolite                       2.20.1
Redmine plugins:
  additionals                    3.0.4-master
  redmine_agile                  1.5.4
  redmine_checklists             3.1.18
  redmine_ckeditor               1.2.3
  redmine_git_hosting            5.0.1-master
  redmine_issue_dynamic_edit     0.7.2

**Comment by toastedcrumpets** [comment] 2021-11-12 08:30
My trace:
E, [2021-11-12T07:51:30.629714 #8] ERROR -- : git: error during get default branch: uninitialized constant #<Class:RedmineGitHosting::Cache::AbstractCache>::Timezone
I, [2021-11-12T07:51:30.635514 #8] INFO -- : Completed 500 Internal Server Error in 34ms (ActiveRecord: 15.5ms)
F, [2021-11-12T07:51:30.636623 #8] FATAL -- :
F, [2021-11-12T07:51:30.636734 #8] FATAL -- : NameError (uninitialized constant #<Class:RedmineGitHosting::Cache::AbstractCache>::Timezone):
F, [2021-11-12T07:51:30.636765 #8] FATAL -- :
F, [2021-11-12T07:51:30.636800 #8] FATAL -- : plugins/redmine_git_hosting/lib/redmine_git_hosting/cache/abstract_cache.rb:59:in `valid_cache_entry?'
plugins/redmine_git_hosting/lib/redmine_git_hosting/cache/database.rb:21:in `get_cache'
plugins/redmine_git_hosting/lib/redmine_git_hosting/cache.rb:22:in `get_cache'
plugins/redmine_git_hosting/lib/redmine_git_hosting/shell_redirector.rb:36:in `execute'
plugins/redmine_git_hosting/lib/redmine/scm/adapters/xitolite_adapter.rb:482:in `git_cmd'
plugins/redmine_git_hosting/lib/redmine/scm/adapters/xitolite_adapter.rb:133:in `entries'
app/models/repository/git.rb:100:in `scm_entries'
app/models/repository.rb:208:in `entries'
app/controllers/repositories_controller.rb:88:in `show'
plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repositories_controller_patch.rb:29:in `show'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
Logs from Nov 12, 2021 to Nov 12, 2021 UTC

**Comment by prahal** [comment] 2022-06-20 20:02
Edit line 59 of plugins/redmine_git_hosting/lib/redmine_git_hosting/cache/abstract_cache.rb and replace `Timezone.now` by `Time.zone.now` and the issue is fixed. (reload the redmine unicorn or alike afterwards to bring the new code in the runtime version.

Clue this was a typo is the version without the missing dot is a few lines above.
Preparing a push request for this fix.

**Comment by PowerKiKi** [comment] 2022-12-15 16:22
Assuming this is fixed in latest release

**Closed by PowerKiKi** 2022-12-15 16:22 UTC
